### PR TITLE
New York Times Clone

### PR DESCRIPTION
**Pull request by ArreyTabe**
This project is about cloning an Article from the New York Times Magazine.
This article has a header, main, aside, and footer sections. To complete these sections we used, HTML, CSS, and GIT.
We used flex, grid, floats for styling the page.

### CODE REVIEW

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
### Request changes 😳
**Hello Developers,** 
I am very happy to see this project and I can see you worked hard on this project but I am sorry to inform you that I cannot approve this project because it is not completed yet.😟 You need to work more on it. 
_It's okay. We are here to learn. Don't get discouraged. Work even harder. You are almost there.😄_
**Please have a look at the suggestions to get more understanding.**

- [ ]  Please handle all validation errors in your code. 

- [x] The New York Times should be a link, not an image only. Please make it image as the original page. 
chrome-capture(24)

- [x] Please make it like the original one by removing the bottom line and changing color and font-size
chrome-capture (25)

- [ ] Make these actual buttons. 
chrome-capture (26)

- [x] These are not in the center. Please make have a look at the original page and make it center. 
chrome-capture (27)

- [x] Your navigation bar is not fixed. Please resolve this issue. 

- [x] All of these sections should be in the center. Please have a look at the original page. 
chrome-capture (28)
In the case of any confusion please have a look at the image below. 
positioning_and_floating_requirements

- [x] Please add images in their respective places as added at the original page. 

chrome-capture (29)

- [x] More popular section of your clone doesn't meet the minimum requirements and is not exactly the clone of the original page. Please have a look and work on it.  

**Original**

chrome-capture (30)

**Yours**

chrome-capture (31)

- [ ] Your footer is not fixed. Please resolve this issue. 
 
**Optional** Please move the live link in the above section of your readme file. 
**Please make the changes and request re-review for the given project**
Stay safe and give me a smile 😇

### Happy Coding
------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

**Review by teekaytech — CHANGES_REQUESTED** [review]
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__I must say, you've done an amazing job so far. However, there are some changes that are required to be fixed before this project can be approved. Please check my points below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [ ] Always update your live demo link whenever one or more changes are added to your project. The current one is not up to date. Please fix it.

- [x] For a reason, the background image at the `The Theory of Inflation` section is not rendering on your page. 
- However, when I cloned your project, it was rendering. Please look into this and make the background image render on your live project.
- Even when it rendered locally, there's a kind of overlapping of the text on the image. Kindly fix this too as you fix the background image.

Source page:


Your page:


- [x] Some work still needs to be done in the `More in Space and Astronomy` and `Most Popular` sections of your page. See the references below:
- Let there be equal white spaces to the left and right side of the section. You're having more white space to the left that the right side.
Source Page


Your Page


- There's a horizontal line on top of the headings. Please add the line, just as we have in the original. 
Source page:


Your page:


- [x] The `Editors' Picks' section is completely missing in your project. Please add it.
**Editors' Picks (Source)**


Your page:


- [x] Some changes are also required in the footer section.
- `The New York Times` logo is a link. Kindly make it a link.
- Add the horizontal line on top of the footer section
- Change the color of your footer text to match the source.


- [ ] You are expected to have a fixed footer at the bottom of your screen. See the footer image below:

Original page:


Your page:


**Please make the required changes and submit another review request when you are done.**

* * *

**_You can reach out to me on twitter (@ola_lere), Github(@teekaytech) or slack (@taofeekolalere )_**
__Happy Coding :smiley:__

**Review by acushlakoncept — CHANGES_REQUESTED** [review]
# Status: Changes Required ♻️

Hello @ArreyTabe and @KinezaEnaelle, Great job! 👏  Both of you have done well on this project.

Both of you have done an awesome job so far 👌. But there are still some changes that are necessary for this project to be approved.

- [ ] Fix the HTML validation warnings/errors, use the [w3 Validator](https://validator.w3.org/)

- [ ]  You are still having text overlapping the background image under the **theory of inflation**
Screen Shot 2020-09-29 at 12 07 54 AM

- [ ] We have to make sure the page design isn't messed up because of different display size, the footer menu is almost ready, please update to match the original. 
ny_footer

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Comment by umairarshadbutt** [comment]
##
## Pull Request under review by Umair Arshad (TSE)

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @ArreyTabe and @KinezaEnaelle,
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindl work on the suggested changes  👇.
- [ ] Fix HTML validation [HTML Validation Screenshort](https://user-images.githubusercontent.com/29689273/94552033-b4a0e200-026f-11eb-9e28-da7ea0e2fa78.png). You can check HTML validations in [validator.w3.org](https://validator.w3.org/) ([screenshot](https://user-images.githubusercontent.com/29689273/94326203-fa358480-ffbb-11ea-81ec-b2704fb93212.png) from Pathwright)

- [ ] Implement the precious TSEs suggestions about navbar and Footer

##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you stick at any point or have any questions, let me know on slack at any time. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Comment by umairarshadbutt** [comment]
##
## Pull Request under review by Umair Arshad (TSE)

**Review by umairarshadbutt — APPROVED** [review]
# **Status: PROJECT APPROVED** :champagne:
Excellent job on this project guys. :fireworks: Keep it up.
##
### The [clone](https://raw.githack.com/KinezaEnaelle/The-New-York-Times-Page-Clone/feature/index.html) shows a good understanding of Positioning and Floating Elements. :100:
##
- The cloned page is rendering as it should and meets all the project specifications.
- The project has a descriptive README.md and is professionally done. Good job with that.
- Pull Request has a meaningful title and a short description.
- CSS is clean. No linter errors at this point and no bad practices used as well.
- The markup as well has no errors nor warnings to show. Good job with that.
- The repo has followed all the guidelines there are to follow (GitHub flow etc.)
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job @ArreyTabe and @KinezaEnaelle! :+1: 
- You can now merge to master and submit the project completion form :rocket: . I wish you all the very best in your next tasks :1st_place_medal:
##
**If you have any questions, let me know on slack at any time. I will be happy to help.**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Pull request merged**
